project_id = "flqzzgwdrdeseyxghqpj"

[functions.extract-from-email]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.send-offer-email]
verify_jwt = false

[functions.receive-offer-email]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.seed-attraction-images]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.import-foils-from-web]
verify_jwt = false

[functions.extract-dominant-color]
verify_jwt = false
